name: awscurl-polling-action
description: CI Tool awscurl-polling-docker action
author: Digitaal Vlaanderen
inputs:

  environment:
    description: 'options ["test", "beta", "tni", "stg", "prd", "acc"]'
    required: true
    default: stg

  version:
    description: 'build version'
    required: true

  status-url:
    description: status url
    required: true

  deploy-url: 
    description: deploy url
    required: true

  access-key:
    description: aws access key
    required: true

  secret-key:
    description: aws secret key
    required: true

  region:
    description: 'region | default: eu-west-1'
    required: false
    default: eu-west-1

  interval:
    description: polling interval in seconds default is 2 seconds
    required: false
    default: 2

  deploy-target:
    description: 'options ["none", "beanstalk", "ecs", "ecs_service", "agb_ecs_service", "ecs_scheduled_task"] | default: none '
    required: false
    default: none

outputs:
  build-uuid:
    description: the build-uuid

  status:
    description: the final status

  final-message:
    description: the final message

runs:
  using: 'docker'
  image: 'docker://ghcr.io/informatievlaanderen/awscurl-polling-action:1.0.10'
  args:
    - ${{ inputs.environment }}
    - ${{ inputs.version }}
    - ${{ inputs.status-url }}
    - ${{ inputs.deploy-url }}
    - ${{ inputs.access-key }}
    - ${{ inputs.secret-key }}
    - ${{ inputs.region }}
    - ${{ inputs.interval }}
    - ${{ inputs.deploy-target }}
branding:
  icon: 'terminal'
  color: 'yellow'
