name: Sample
on:
  workflow_dispatch
jobs:
  one:
      runs-on: ubuntu-latest
      steps:
        - name: awscurl-polling-action
          id: awscurl-polling-action
          uses: informatievlaanderen/awscurl-polling-action@main
          with:
            environment: stg
            version: ${{ secrets.VERSION }}
            status-url: ${{ secrets.STATUS_URL }}
            deploy-url: ${{ secrets.DEPLOY_URL }}
            access-key: ${{ secrets.ACCESS_KEY }}
            secret-key: ${{ secrets.SECRET_KEY }}
            region: eu-west-1
            interval: 2
        - name: output
          shell: bash
          run: |
            echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
            echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
            echo ${{ steps.awscurl-polling-action.outputs.final-message }}